// resources/js-vue/Pages/Other.vue
<script setup lang="ts">
import { computed, ref } from 'vue';
import DefaultLayout from '../Layouts/DefaultLayout.vue';

const name = ref('');
const hasName = computed(() => name.value.length > 0);

</script>

<template>
	<DefaultLayout>
		<input v-model.lazy.trim="name">
		<div v-if="hasName">
			Hello, {{ name }}
		</div>
	</DefaultLayout>
</template>

// resources/js-react/Pages/Other.jsx
import { useState } from 'react';
import DefaultLayout from '../Layouts/DefaultLayout';

export default function OtherPage(){
	const [ name, setName ] = useState('');

	return <DefaultLayout>
		<input value={name} onChange={e => setName(e.target.value.trim())} />
		{ name.length > 0 && <div>
			Hello, { name }
		</div> }
	</DefaultLayout>
}
